baseURL       = "https://howweletgo.org/"
languageCode  = "en-gb"
title         = "How we let go (of faith beliefs)"
theme         = "letgo"
enableGitInfo = true

[params]
description    ="A data-driven portrait of the process of letting go"

